# Generated by Django 3.0.1 on 2020-01-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apylien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textualcontent',
            name='extra',
            field=models.CharField(default='na', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textualcontext', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apylien.Textualcontent')),
            ],
        ),
    ]
