# Generated by Django 3.0.1 on 2020-01-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apylien', '0002_textualcontent_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textualcontent',
            name='customuser',
        ),
    ]
