# Generated by Django 3.0.1 on 2020-01-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apylien', '0002_auto_20200102_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreport',
            name='textualcontext',
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='complete',
            field=models.BooleanField(default=0, max_length=43),
        ),
    ]
