# Generated by Django 3.0.1 on 2020-01-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apylien', '0004_textualcontent_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='textualcontent',
            name='classify',
            field=models.BooleanField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='textualcontent',
            name='concept',
            field=models.BooleanField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='textualcontent',
            name='elsa',
            field=models.BooleanField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='textualcontent',
            name='sentiment',
            field=models.BooleanField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='textualcontent',
            name='summarize',
            field=models.BooleanField(default=0, max_length=2),
        ),
    ]
